version: '3.6'
services:
  jupyterlab:
    image: dp-recsys:latest
    build: .
    ports:
      - '8888:8888'
    volumes:
      - ./:/home
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    command: conda run --no-capture-output sh -c "jupyter lab --ip 0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"
